//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseMaterial
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public Nullable<int> MaterialTypeID { get; set; }
        public Nullable<int> Period { get; set; }
        public string Details { get; set; }
        public Nullable<int> OrderId { get; set; }
        public bool Active { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<System.DateTime> Created_At { get; set; }
        public Nullable<System.DateTime> Updated_At { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual MaterialType MaterialType { get; set; }
    }
}
