//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EWork.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Members
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string noties { get; set; }
        public bool Active { get; set; }
        public int userid { get; set; }
        public string AddedBy { get; set; }
        public Nullable<System.DateTime> AddedAt { get; set; }
        public string pic { get; set; }
        public string Email { get; set; }
    
        public virtual users users { get; set; }
    }
}
